/******************************************************************************
* Copyright (C) 2009 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.23                                                         *
******************************************************************************/

#ifndef IPFCOMPETITIONSBYSEASONDAO_H_
#define IPFCOMPETITIONSBYSEASONDAO_H_

#include <string>
#include <vector>

#include "../bean/CPfCompetitionsBySeason.h"

class IPfCompetitionsBySeasonDAO
{
public:
    IPfCompetitionsBySeasonDAO(){}
    virtual ~IPfCompetitionsBySeasonDAO(){}

    virtual bool deleteReg(CPfCompetitionsBySeason *reg) =0;
    virtual bool insertReg(CPfCompetitionsBySeason *reg) =0;
    virtual bool updateReg(CPfCompetitionsBySeason *reg) =0;

    virtual void freeVector(std::vector<CPfCompetitionsBySeason*>* vector) =0;

    virtual std::vector<CPfCompetitionsBySeason*>* findByXFkSeason(int XFkSeason) =0;
    virtual std::vector<CPfCompetitionsBySeason*>* findByXFkSeason(const std::string &XFkSeason) =0;
    virtual CPfCompetitionsBySeason* findByXCompetitionBySeason(int XCompetitionBySeason) =0;
    virtual CPfCompetitionsBySeason* findByXCompetitionBySeason(const std::string &XCompetitionBySeason) =0;
    virtual std::vector<CPfCompetitionsBySeason*>* findByXFkCompetition(int XFkCompetition) =0;
    virtual std::vector<CPfCompetitionsBySeason*>* findByXFkCompetition(const std::string &XFkCompetition) =0;
    virtual CPfCompetitionsBySeason* findByXFkSeasonAndXTeam(int XFkSeason, int XTeam) =0;
    virtual CPfCompetitionsBySeason* findByXFkSeasonAndXTeam(const std::string &XFkSeason, const std::string &XTeam) =0;

};
#endif /*IPFCOMPETITIONSBYSEASONDAO_H_*/
