/******************************************************************************
* Copyright (C) 2009 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.23                                                         *
******************************************************************************/

#ifndef IPFCONFEDERATIONSDAO_H_
#define IPFCONFEDERATIONSDAO_H_

#include <string>
#include <vector>

#include "../bean/CPfConfederations.h"

class IPfConfederationsDAO
{
public:
    IPfConfederationsDAO(){}
    virtual ~IPfConfederationsDAO(){}

    virtual bool deleteReg(CPfConfederations *reg) =0;
    virtual bool insertReg(CPfConfederations *reg) =0;
    virtual bool updateReg(CPfConfederations *reg) =0;

    virtual void freeVector(std::vector<CPfConfederations*>* vector) =0;

    virtual CPfConfederations* findByXConfederation(int XConfederation) =0;
    virtual CPfConfederations* findByXConfederation(const std::string &XConfederation) =0;
    virtual std::vector<CPfConfederations*>* findAll() =0;
    virtual std::vector<CPfConfederations*>* findByXFKSeasonWithLeague(int XFKSeason) =0;
    virtual std::vector<CPfConfederations*>* findByXFKSeasonWithLeague(const std::string &XFKSeason) =0;

};
#endif /*IPFCONFEDERATIONSDAO_H_*/
