/******************************************************************************
* Copyright (C) 2009 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.23                                                         *
******************************************************************************/

#ifndef CPFFORMATIONSDAOSQLITE_H_
#define CPFFORMATIONSDAOSQLITE_H_

#include <string>
#include <sqlite3.h>

#include "entity/CPfFormationsDAOSQLiteEntity.h"
#include "../../bean/CPfFormations.h"

class CPfFormationsDAOSQLite : public CPfFormationsDAOSQLiteEntity
{
public:
    CPfFormationsDAOSQLite(sqlite3 *database);
    virtual ~CPfFormationsDAOSQLite();

    virtual CPfFormations* findByXFkCoachOwner(int XFkCoachOwner);
    virtual CPfFormations* findByXFkCoachOwner(const std::string &XFkCoachOwner);
    virtual CPfFormations* findByXFormation(int XFormation);
    virtual CPfFormations* findByXFormation(const std::string &XFormation);
    virtual CPfFormations* findActiveByXTeam(int XTeam, const std::string &timestamp);
	virtual CPfFormations* findActiveByXTeam(const std::string &XTeam, const std::string &timestamp);
	virtual std::vector<CPfFormations*>* findByXTeam(int XTeam, const std::string &timestamp);
	virtual std::vector<CPfFormations*>* findByXTeam(const std::string &XTeam, const std::string &timestamp);

};
#endif /*CPFFORMATIONSDAOSQLITE_H_*/
