/******************************************************************************
* Copyright (C) 2009 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.23                                                         *
******************************************************************************/

#include <iostream>
#include <sstream>
#include <stdlib.h>

#include "CPfCoaches.h"

CPfCoaches::CPfCoaches()
{
    m_XCoach = "0";
    m_SShortName = "";
    m_SName = "";
    m_SPhoto = "";
    m_DBirthday = "";
    m_XFkCountry = "0";
    m_XFkFormationSelected = "0";
}

CPfCoaches::CPfCoaches(const CPfCoaches &obj)
{
    m_XCoach = obj.m_XCoach;
    m_SShortName = obj.m_SShortName;
    m_SName = obj.m_SName;
    m_SPhoto = obj.m_SPhoto;
    m_DBirthday = obj.m_DBirthday;
    m_XFkCountry = obj.m_XFkCountry;
    m_XFkFormationSelected = obj.m_XFkFormationSelected;
}

CPfCoaches::~CPfCoaches()
{
}

int CPfCoaches::getXCoach() const
{
    if( m_XCoach=="" ){
        return 0;
    }else{
        return atoi(m_XCoach.c_str());
    }
}

const std::string& CPfCoaches::getXCoach_str() const
{
    return m_XCoach;
}

const std::string& CPfCoaches::getSShortName() const
{
    return m_SShortName;
}

const std::string& CPfCoaches::getSShortName_str() const
{
    return m_SShortName;
}

const std::string& CPfCoaches::getSName() const
{
    return m_SName;
}

const std::string& CPfCoaches::getSName_str() const
{
    return m_SName;
}

const std::string& CPfCoaches::getSPhoto() const
{
    return m_SPhoto;
}

const std::string& CPfCoaches::getSPhoto_str() const
{
    return m_SPhoto;
}

CDate CPfCoaches::getDBirthday() const
{
    return m_DBirthday;
}

const std::string& CPfCoaches::getDBirthday_str() const
{
    return m_DBirthday;
}

int CPfCoaches::getXFkCountry() const
{
    if( m_XFkCountry=="" ){
        return 0;
    }else{
        return atoi(m_XFkCountry.c_str());
    }
}

const std::string& CPfCoaches::getXFkCountry_str() const
{
    return m_XFkCountry;
}

int CPfCoaches::getXFkFormationSelected() const
{
    if( m_XFkFormationSelected=="" ){
        return 0;
    }else{
        return atoi(m_XFkFormationSelected.c_str());
    }
}

const std::string& CPfCoaches::getXFkFormationSelected_str() const
{
    return m_XFkFormationSelected;
}

void CPfCoaches::setXCoach(int XCoach)
{
    std::ostringstream stream;
    stream << XCoach;
    m_XCoach = stream.str();
}

void CPfCoaches::setXCoach_str(const std::string &XCoach)
{
    m_XCoach = XCoach;
}

void CPfCoaches::setSShortName(const std::string &SShortName)
{
    m_SShortName = SShortName;
}

void CPfCoaches::setSShortName_str(const std::string &SShortName)
{
    m_SShortName = SShortName;
}

void CPfCoaches::setSName(const std::string &SName)
{
    m_SName = SName;
}

void CPfCoaches::setSName_str(const std::string &SName)
{
    m_SName = SName;
}

void CPfCoaches::setSPhoto(const std::string &SPhoto)
{
    m_SPhoto = SPhoto;
}

void CPfCoaches::setSPhoto_str(const std::string &SPhoto)
{
    m_SPhoto = SPhoto;
}

void CPfCoaches::setDBirthday(const CDate &DBirthday)
{
    m_DBirthday = DBirthday.getTimestamp();
}

void CPfCoaches::setDBirthday_str(const std::string &DBirthday)
{
    m_DBirthday = DBirthday;
}

void CPfCoaches::setXFkCountry(int XFkCountry)
{
    std::ostringstream stream;
    stream << XFkCountry;
    m_XFkCountry = stream.str();
}

void CPfCoaches::setXFkCountry_str(const std::string &XFkCountry)
{
    m_XFkCountry = XFkCountry;
}

void CPfCoaches::setXFkFormationSelected(int XFkFormationSelected)
{
    std::ostringstream stream;
    stream << XFkFormationSelected;
    m_XFkFormationSelected = stream.str();
}

void CPfCoaches::setXFkFormationSelected_str(const std::string &XFkFormationSelected)
{
    m_XFkFormationSelected = XFkFormationSelected;
}

