/******************************************************************************
* Copyright (C) 2009 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.23                                                         *
******************************************************************************/

#include <iostream>
#include <sstream>
#include <stdlib.h>

#include "CPfScorers.h"

CPfScorers::CPfScorers()
{
    m_NGoals = "0";
    m_STeamPlayer = "";
    m_STeam = "";
}

CPfScorers::CPfScorers(const CPfScorers &obj)
{
    m_NGoals = obj.m_NGoals;
    m_STeamPlayer = obj.m_STeamPlayer;
    m_STeam = obj.m_STeam;
}

CPfScorers::~CPfScorers()
{
}

int CPfScorers::getNGoals() const
{
    if( m_NGoals=="" ){
        return 0;
    }else{
        return atoi(m_NGoals.c_str());
    }
}

const std::string& CPfScorers::getNGoals_str() const
{
    return m_NGoals;
}

const std::string& CPfScorers::getSTeamPlayer() const
{
    return m_STeamPlayer;
}

const std::string& CPfScorers::getSTeamPlayer_str() const
{
    return m_STeamPlayer;
}

const std::string& CPfScorers::getSTeam() const
{
    return m_STeam;
}

const std::string& CPfScorers::getSTeam_str() const
{
    return m_STeam;
}

void CPfScorers::setNGoals(int NGoals)
{
    std::ostringstream stream;
    stream << NGoals;
    m_NGoals = stream.str();
}

void CPfScorers::setNGoals_str(const std::string &NGoals)
{
    m_NGoals = NGoals;
}

void CPfScorers::setSTeamPlayer(const std::string &STeamPlayer)
{
    m_STeamPlayer = STeamPlayer;
}

void CPfScorers::setSTeamPlayer_str(const std::string &STeamPlayer)
{
    m_STeamPlayer = STeamPlayer;
}

void CPfScorers::setSTeam(const std::string &STeam)
{
    m_STeam = STeam;
}

void CPfScorers::setSTeam_str(const std::string &STeam)
{
    m_STeam = STeam;
}

