/******************************************************************************
* Copyright (C) 2008 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.20                                                         *
******************************************************************************/

#ifndef CPFTEAMPLAYERS_H_
#define CPFTEAMPLAYERS_H_

#include <string>

class CPfTeamPlayers
{
public:
    CPfTeamPlayers();
    CPfTeamPlayers(const CPfTeamPlayers &obj);
    virtual ~CPfTeamPlayers();

    int getNKickPower() const;
    const std::string& getNKickPower_str() const;
    int getNVelocity() const;
    const std::string& getNVelocity_str() const;
    int getXTeamPlayer() const;
    const std::string& getXTeamPlayer_str() const;
    const std::string& getSShortName() const;
    const std::string& getSShortName_str() const;
    const std::string& getSName() const;
    const std::string& getSName_str() const;
    int getXFkCountry() const;
    const std::string& getXFkCountry_str() const;

    void setNKickPower(int NKickPower);
    void setNKickPower_str(const std::string &NKickPower);
    void setNVelocity(int NVelocity);
    void setNVelocity_str(const std::string &NVelocity);
    void setXTeamPlayer(int XTeamPlayer);
    void setXTeamPlayer_str(const std::string &XTeamPlayer);
    void setSShortName(const std::string &SShortName);
    void setSShortName_str(const std::string &SShortName);
    void setSName(const std::string &SName);
    void setSName_str(const std::string &SName);
    void setXFkCountry(int XFkCountry);
    void setXFkCountry_str(const std::string &XFkCountry);

private:
    std::string m_NKickPower;
    std::string m_NVelocity;
    std::string m_XTeamPlayer;
    std::string m_SShortName;
    std::string m_SName;
    std::string m_XFkCountry;

};
#endif /*CPFTEAMPLAYERS_H_*/
