/******************************************************************************
* Copyright (C) 2008 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.16                                                         *
******************************************************************************/

#include <iostream>
#include <sstream>
#include <stdlib.h>

#include "CPfGameStates.h"

CPfGameStates::CPfGameStates()
{
    m_SState = "";
    m_XState = "0";
    m_SValue = "";
}

CPfGameStates::CPfGameStates(const CPfGameStates &obj)
{
    m_SState = obj.m_SState;
    m_XState = obj.m_XState;
    m_SValue = obj.m_SValue;
}

CPfGameStates::~CPfGameStates()
{
}

const std::string& CPfGameStates::getSState() const
{
    return m_SState;
}

const std::string& CPfGameStates::getSState_str() const
{
    return m_SState;
}

int CPfGameStates::getXState() const
{
    if( m_XState=="" ){
        return 0;
    }else{
        return atoi(m_XState.c_str());
    }
}

const std::string& CPfGameStates::getXState_str() const
{
    return m_XState;
}

const std::string& CPfGameStates::getSValue() const
{
    return m_SValue;
}

const std::string& CPfGameStates::getSValue_str() const
{
    return m_SValue;
}

void CPfGameStates::setSState(const std::string &SState)
{
    m_SState = SState;
}

void CPfGameStates::setSState_str(const std::string &SState)
{
    m_SState = SState;
}

void CPfGameStates::setXState(int XState)
{
    std::ostringstream stream;
    stream << XState;
    m_XState = stream.str();
}

void CPfGameStates::setXState_str(const std::string &XState)
{
    m_XState = XState;
}

void CPfGameStates::setSValue(const std::string &SValue)
{
    m_SValue = SValue;
}

void CPfGameStates::setSValue_str(const std::string &SValue)
{
    m_SValue = SValue;
}

