/******************************************************************************
* Copyright (C) 2008 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.4                                                          *
******************************************************************************/

#include <iostream>
#include <sstream>

#include "CPfPaises.h"

CPfPaises::CPfPaises()
{
    m_SPais = "";
    m_XPais = "0";
    m_SRutaBandera = "";
}

CPfPaises::~CPfPaises()
{
}

const std::string* CPfPaises::getSPais()
{
    return &m_SPais;
}

int CPfPaises::getXPais_int()
{
    return atoi(m_XPais.c_str());
}

const std::string* CPfPaises::getXPais()
{
    return &m_XPais;
}

const std::string* CPfPaises::getSRutaBandera()
{
    return &m_SRutaBandera;
}

void CPfPaises::setSPais(const std::string SPais)
{
    m_SPais = SPais;
}

void CPfPaises::setXPais(int XPais)
{
    std::ostringstream stream;
    stream << XPais;
    m_XPais = stream.str();
}

void CPfPaises::setXPais(const std::string XPais)
{
    m_XPais = XPais;
}

void CPfPaises::setSRutaBandera(const std::string SRutaBandera)
{
    m_SRutaBandera = SRutaBandera;
}

