/******************************************************************************
* Copyright (C) 2008 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.18                                                         *
******************************************************************************/

#include <iostream>
#include <sstream>

#include "CPfRegisteredTeams.h"

CPfRegisteredTeams::CPfRegisteredTeams()
{
    m_XRegisteredTeam = "0";
    m_XFkCompetition = "0";
    m_XFkTeam = "0";
}

CPfRegisteredTeams::CPfRegisteredTeams(const CPfRegisteredTeams &obj)
{
    m_XRegisteredTeam = obj.m_XRegisteredTeam;
    m_XFkCompetition = obj.m_XFkCompetition;
    m_XFkTeam = obj.m_XFkTeam;
}

CPfRegisteredTeams::~CPfRegisteredTeams()
{
}

int CPfRegisteredTeams::getXRegisteredTeam() const
{
    if( m_XRegisteredTeam=="" ){
        return 0;
    }else{
        return atoi(m_XRegisteredTeam.c_str());
    }
}

const std::string& CPfRegisteredTeams::getXRegisteredTeam_str() const
{
    return m_XRegisteredTeam;
}

int CPfRegisteredTeams::getXFkCompetition() const
{
    if( m_XFkCompetition=="" ){
        return 0;
    }else{
        return atoi(m_XFkCompetition.c_str());
    }
}

const std::string& CPfRegisteredTeams::getXFkCompetition_str() const
{
    return m_XFkCompetition;
}

int CPfRegisteredTeams::getXFkTeam() const
{
    if( m_XFkTeam=="" ){
        return 0;
    }else{
        return atoi(m_XFkTeam.c_str());
    }
}

const std::string& CPfRegisteredTeams::getXFkTeam_str() const
{
    return m_XFkTeam;
}

void CPfRegisteredTeams::setXRegisteredTeam(int XRegisteredTeam)
{
    std::ostringstream stream;
    stream << XRegisteredTeam;
    m_XRegisteredTeam = stream.str();
}

void CPfRegisteredTeams::setXRegisteredTeam_str(const std::string &XRegisteredTeam)
{
    m_XRegisteredTeam = XRegisteredTeam;
}

void CPfRegisteredTeams::setXFkCompetition(int XFkCompetition)
{
    std::ostringstream stream;
    stream << XFkCompetition;
    m_XFkCompetition = stream.str();
}

void CPfRegisteredTeams::setXFkCompetition_str(const std::string &XFkCompetition)
{
    m_XFkCompetition = XFkCompetition;
}

void CPfRegisteredTeams::setXFkTeam(int XFkTeam)
{
    std::ostringstream stream;
    stream << XFkTeam;
    m_XFkTeam = stream.str();
}

void CPfRegisteredTeams::setXFkTeam_str(const std::string &XFkTeam)
{
    m_XFkTeam = XFkTeam;
}

