/******************************************************************************
* Copyright (C) 2007 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.1                                                          *
******************************************************************************/


#ifndef __CPfEquiposDAOSqliteEntity_H_
#define __CPfEquiposDAOSqliteEntity_H_

#include <string>
#include <vector>

#include "IPfEquiposDAO.h"

using namespace std;


class CPfEquiposDAOSqliteEntity : public IPfEquiposDAO
{

public:
    CPfEquiposDAOSqliteEntity(sqlite3 *dataBase);
    virtual ~CPfEquiposDAOSqliteEntity();

    virtual bool deleteReg(CPfEquipos * elem);
    virtual bool insert(CPfEquipos * elem);
    virtual bool update(CPfEquipos * elem);

protected:
    CPfEquipos* loadRegister(string sql);
    vector<CPfEquipos*> * loadVector(string sql);

private:
    sqlite3 *m_dataBase;

    bool exec(string sql);
    static int callbackRegister(void *object, int nColumns, char **vColumn, char **sColumn );
    static int callbackVector(void *object, int nColumns, char **vColumn, char **sColumn );

};
#endif // __CPfEquiposDAOSqliteEntity_H__
