/******************************************************************************
* Copyright (C) 2009 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.23                                                         *
******************************************************************************/

#include <iostream>
#include <sstream>
#include <stdlib.h>

#include "CPfDemarcations.h"

CPfDemarcations::CPfDemarcations()
{
    m_SShortName = "";
    m_XDemarcation = "0";
    m_SName = "";
}

CPfDemarcations::CPfDemarcations(const CPfDemarcations &obj)
{
    m_SShortName = obj.m_SShortName;
    m_XDemarcation = obj.m_XDemarcation;
    m_SName = obj.m_SName;
}

CPfDemarcations::~CPfDemarcations()
{
}

const std::string& CPfDemarcations::getSShortName() const
{
    return m_SShortName;
}

const std::string& CPfDemarcations::getSShortName_str() const
{
    return m_SShortName;
}

int CPfDemarcations::getXDemarcation() const
{
    if( m_XDemarcation=="" ){
        return 0;
    }else{
        return atoi(m_XDemarcation.c_str());
    }
}

const std::string& CPfDemarcations::getXDemarcation_str() const
{
    return m_XDemarcation;
}

const std::string& CPfDemarcations::getSName() const
{
    return m_SName;
}

const std::string& CPfDemarcations::getSName_str() const
{
    return m_SName;
}

void CPfDemarcations::setSShortName(const std::string &SShortName)
{
    m_SShortName = SShortName;
}

void CPfDemarcations::setSShortName_str(const std::string &SShortName)
{
    m_SShortName = SShortName;
}

void CPfDemarcations::setXDemarcation(int XDemarcation)
{
    std::ostringstream stream;
    stream << XDemarcation;
    m_XDemarcation = stream.str();
}

void CPfDemarcations::setXDemarcation_str(const std::string &XDemarcation)
{
    m_XDemarcation = XDemarcation;
}

void CPfDemarcations::setSName(const std::string &SName)
{
    m_SName = SName;
}

void CPfDemarcations::setSName_str(const std::string &SName)
{
    m_SName = SName;
}

