/******************************************************************************
* Copyright (C) 2009 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.23                                                         *
******************************************************************************/

#include <iostream>
#include <sstream>
#include <stdlib.h>

#include "CPfTeamPlayerAverages.h"

CPfTeamPlayerAverages::CPfTeamPlayerAverages()
{
    m_XTeamPlayer = "0";
    m_NTotal = "0";
    m_NAttack = "0";
    m_NDefense = "0";
}

CPfTeamPlayerAverages::CPfTeamPlayerAverages(const CPfTeamPlayerAverages &obj)
{
    m_XTeamPlayer = obj.m_XTeamPlayer;
    m_NTotal = obj.m_NTotal;
    m_NAttack = obj.m_NAttack;
    m_NDefense = obj.m_NDefense;
}

CPfTeamPlayerAverages::~CPfTeamPlayerAverages()
{
}

int CPfTeamPlayerAverages::getXTeamPlayer() const
{
    if( m_XTeamPlayer=="" ){
        return 0;
    }else{
        return atoi(m_XTeamPlayer.c_str());
    }
}

const std::string& CPfTeamPlayerAverages::getXTeamPlayer_str() const
{
    return m_XTeamPlayer;
}

int CPfTeamPlayerAverages::getNTotal() const
{
    if( m_NTotal=="" ){
        return 0;
    }else{
        return atoi(m_NTotal.c_str());
    }
}

const std::string& CPfTeamPlayerAverages::getNTotal_str() const
{
    return m_NTotal;
}

int CPfTeamPlayerAverages::getNAttack() const
{
    if( m_NAttack=="" ){
        return 0;
    }else{
        return atoi(m_NAttack.c_str());
    }
}

const std::string& CPfTeamPlayerAverages::getNAttack_str() const
{
    return m_NAttack;
}

int CPfTeamPlayerAverages::getNDefense() const
{
    if( m_NDefense=="" ){
        return 0;
    }else{
        return atoi(m_NDefense.c_str());
    }
}

const std::string& CPfTeamPlayerAverages::getNDefense_str() const
{
    return m_NDefense;
}

void CPfTeamPlayerAverages::setXTeamPlayer(int XTeamPlayer)
{
    std::ostringstream stream;
    stream << XTeamPlayer;
    m_XTeamPlayer = stream.str();
}

void CPfTeamPlayerAverages::setXTeamPlayer_str(const std::string &XTeamPlayer)
{
    m_XTeamPlayer = XTeamPlayer;
}

void CPfTeamPlayerAverages::setNTotal(int NTotal)
{
    std::ostringstream stream;
    stream << NTotal;
    m_NTotal = stream.str();
}

void CPfTeamPlayerAverages::setNTotal_str(const std::string &NTotal)
{
    m_NTotal = NTotal;
}

void CPfTeamPlayerAverages::setNAttack(int NAttack)
{
    std::ostringstream stream;
    stream << NAttack;
    m_NAttack = stream.str();
}

void CPfTeamPlayerAverages::setNAttack_str(const std::string &NAttack)
{
    m_NAttack = NAttack;
}

void CPfTeamPlayerAverages::setNDefense(int NDefense)
{
    std::ostringstream stream;
    stream << NDefense;
    m_NDefense = stream.str();
}

void CPfTeamPlayerAverages::setNDefense_str(const std::string &NDefense)
{
    m_NDefense = NDefense;
}

