/******************************************************************************
* Copyright (C) 2008 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.18                                                         *
******************************************************************************/

#ifndef IPFREGISTEREDTEAMSDAO_H_
#define IPFREGISTEREDTEAMSDAO_H_

#include <string>
#include <vector>

#include "../bean/CPfRegisteredTeams.h"

class IPfRegisteredTeamsDAO
{
public:
    IPfRegisteredTeamsDAO(){}
    virtual ~IPfRegisteredTeamsDAO(){}

    virtual bool deleteReg(CPfRegisteredTeams *reg) =0;
    virtual bool insertReg(CPfRegisteredTeams *reg) =0;
    virtual bool updateReg(CPfRegisteredTeams *reg) =0;

    virtual void freeVector(std::vector<CPfRegisteredTeams*>* vector) =0;

    virtual CPfRegisteredTeams* findByXRegisteredTeam(int XRegisteredTeam) =0;
    virtual CPfRegisteredTeams* findByXRegisteredTeam(const std::string &XRegisteredTeam) =0;
    virtual CPfRegisteredTeams* findByXFkCompetition(int XFkCompetition) =0;
    virtual CPfRegisteredTeams* findByXFkCompetition(const std::string &XFkCompetition) =0;
    virtual CPfRegisteredTeams* findByXFkTeam(int XFkTeam) =0;
    virtual CPfRegisteredTeams* findByXFkTeam(const std::string &XFkTeam) =0;

};
#endif /*IPFREGISTEREDTEAMSDAO_H_*/
