/******************************************************************************
* Copyright (C) 2007 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.0                                                          *
******************************************************************************/


#ifndef __CPfSavedGames_H__
#define __CPfSavedGames_H__

#include <string>

using namespace std;


class CPfSavedGames
{
public:

    CPfSavedGames();
    CPfSavedGames(string SUser, string SConnectionString, 
        string SSavedGame, string XSavedGame, 
        string SDriver);
    ~CPfSavedGames();

    void setSUser(string SUser);
    void setSConnectionString(string SConnectionString);
    void setSSavedGame(string SSavedGame);
    void setXSavedGame(string XSavedGame);
    void setSDriver(string SDriver);
    const string* getSUser();
    const string* getSConnectionString();
    const string* getSSavedGame();
    const string* getXSavedGame();
    const string* getSDriver();

private:
    string *m_SUser;
    string *m_SConnectionString;
    string *m_SSavedGame;
    string *m_XSavedGame;
    string *m_SDriver;
};

#endif // __CPfSavedGames_H__ 

