/******************************************************************************
* Copyright (C) 2009 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.23                                                         *
******************************************************************************/

#ifndef IPFCOUNTRIESDAO_H_
#define IPFCOUNTRIESDAO_H_

#include <string>
#include <vector>

#include "../bean/CPfCountries.h"

class IPfCountriesDAO
{
public:
    IPfCountriesDAO(){}
    virtual ~IPfCountriesDAO(){}

    virtual bool deleteReg(CPfCountries *reg) =0;
    virtual bool insertReg(CPfCountries *reg) =0;
    virtual bool updateReg(CPfCountries *reg) =0;

    virtual void freeVector(std::vector<CPfCountries*>* vector) =0;

	virtual std::vector<CPfCountries *> *getAllCounties() = 0;
    virtual CPfCountries* findByXCountry(int XCountry) =0;
    virtual CPfCountries* findByXCountry(const std::string &XCountry) =0;
    virtual std::vector<CPfCountries*>* findByXFkConfederation(int XFkConfederation) =0;
    virtual std::vector<CPfCountries*>* findByXFkConfederation(const std::string &XFkConfederation) =0;
    virtual std::vector<CPfCountries*>* findByXFkConfederationAndXFKSeasonWithLeague(int XFkConfederation, int XFKSeason) =0;
    virtual std::vector<CPfCountries*>* findByXFkConfederationAndXFKSeasonWithLeague(const std::string &XFkConfederation, const std::string &XFKSeason) =0;
	virtual std::vector<CPfCountries *>* findByName(const std::string &name) = 0;

};
#endif /*IPFCOUNTRIESDAO_H_*/
