/******************************************************************************
* Copyright (C) 2009 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.23                                                         *
******************************************************************************/

#ifndef IPFSTRATEGICPOSITIONDAO_H_
#define IPFSTRATEGICPOSITIONDAO_H_

#include <string>
#include <vector>

#include "../bean/CPfStrategicPosition.h"

class IPfStrategicPositionDAO
{
public:
    IPfStrategicPositionDAO(){}
    virtual ~IPfStrategicPositionDAO(){}

    virtual bool deleteReg(CPfStrategicPosition *reg) =0;
    virtual bool insertReg(CPfStrategicPosition *reg) =0;
    virtual bool updateReg(CPfStrategicPosition *reg) =0;

    virtual void freeVector(std::vector<CPfStrategicPosition*>* vector) =0;

    virtual CPfStrategicPosition* findByXFkFormation(int XFkFormation) =0;
    virtual CPfStrategicPosition* findByXFkFormation(const std::string &XFkFormation) =0;
    virtual CPfStrategicPosition* findByXFkRole(int XFkRole) =0;
    virtual CPfStrategicPosition* findByXFkRole(const std::string &XFkRole) =0;
    virtual CPfStrategicPosition* findByXStrategicPosition(int XStrategicPosition) =0;
    virtual CPfStrategicPosition* findByXStrategicPosition(const std::string &XStrategicPosition) =0;

};
#endif /*IPFSTRATEGICPOSITIONDAO_H_*/
