/******************************************************************************
* Copyright (C) 2010 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.23                                                         *
******************************************************************************/

#include <stdlib.h>
#include <string.h>

#include "CPfPhaseTypesDAOSQLiteEntity.h"
#include "../../../../../exceptions/PFException.h"
#include "../../../../../utils/CLog.h"

CPfPhaseTypesDAOSQLiteEntity::CPfPhaseTypesDAOSQLiteEntity(sqlite3 *database)
{
    m_database = database;
}

CPfPhaseTypesDAOSQLiteEntity::~CPfPhaseTypesDAOSQLiteEntity()
{
}

void CPfPhaseTypesDAOSQLiteEntity::setSQLite(sqlite3 *database)
{
    m_database = database;
}

bool CPfPhaseTypesDAOSQLiteEntity::deleteReg(CPfPhaseTypes *reg)
{
    std::string sql("DELETE FROM PF_PHASE_TYPES WHERE X_PHASE_TYPE=");
    sql += "'"+reg->getXPhaseType_str()+"'";
    return exec(sql);
}

bool CPfPhaseTypesDAOSQLiteEntity::insertReg(CPfPhaseTypes *reg)
{
    std::string sql("INSERT INTO PF_PHASE_TYPES (S_PHASE_TYPE) VALUES (");
    sql += (reg->getSPhaseType_str()=="")?"NULL":"'"+reg->getSPhaseType_str()+"'";
    sql += ")";
    if( exec(sql) ){
        reg->setXPhaseType(sqlite3_last_insert_rowid(m_database));
        return true;
    }else{
        return false;
    }
}

bool CPfPhaseTypesDAOSQLiteEntity::updateReg(CPfPhaseTypes *reg)
{
    std::string sql("UPDATE PF_PHASE_TYPES SET ");
    sql += (reg->getSPhaseType_str()=="")?" S_PHASE_TYPE=NULL":" S_PHASE_TYPE='"+reg->getSPhaseType_str()+"'";
    sql += (reg->getXPhaseType_str()=="")?",X_PHASE_TYPE=NULL":",X_PHASE_TYPE='"+reg->getXPhaseType_str()+"'";
    sql += " WHERE X_PHASE_TYPE='"+reg->getXPhaseType_str()+"'";
    return exec(sql);
}

void CPfPhaseTypesDAOSQLiteEntity::freeVector(std::vector<CPfPhaseTypes*>* vector )
{
    std::vector<CPfPhaseTypes*>::iterator it;
    for( it=vector->begin(); it!=vector->end(); it++ ){
        delete (*it);
        (*it) = NULL;
    }
    delete vector;
}

CPfPhaseTypes* CPfPhaseTypesDAOSQLiteEntity::loadRegister(const std::string &sql)
{
    if( m_database==NULL ){
        throw PFEXCEPTION("No database connection.");
    }

    char *msgError = NULL;
    CPfPhaseTypes *destiny = new CPfPhaseTypes();
    int result = sqlite3_exec(m_database, sql.c_str(), callbackRegister, destiny, &msgError);
    if( result!=SQLITE_OK && result!=SQLITE_ABORT ){
        LOG_ERROR("Error in SQL: \"%s\" --> \"%s\"", sql.c_str(), msgError);
    }
    if( msgError!=NULL ){ 
        sqlite3_free(msgError);
    }
    return destiny;
}

std::vector<CPfPhaseTypes*> * CPfPhaseTypesDAOSQLiteEntity::loadVector(const std::string &sql)
{
    if( m_database==NULL ){
        throw PFEXCEPTION("No database connection.");
    }

    char *msgError = NULL;
    std::vector<CPfPhaseTypes*> *container = new std::vector<CPfPhaseTypes*>;
    int result = sqlite3_exec(m_database, sql.c_str(), callbackVector, container, &msgError);
    if( result!=SQLITE_OK ){
        LOG_ERROR("Error in SQL: \"%s\" --> \"%s\"", sql.c_str(), msgError);
    }
    if( msgError!=NULL ){ 
        sqlite3_free(msgError);
    }
    return container;
}

bool CPfPhaseTypesDAOSQLiteEntity::exec(const std::string &sql)
{
    if( m_database==NULL ){
        throw PFEXCEPTION("No database connection.");
    }

    char *msgError = NULL;
    bool correct = true;
    int result = sqlite3_exec(m_database, sql.c_str(), NULL, NULL, &msgError);
    if( result!=SQLITE_OK ){
        LOG_ERROR("Error in SQL: \"%s\" --> \"%s\"", sql.c_str(), msgError);
        correct = false;
    }
    if( msgError!=NULL ){ 
        sqlite3_free(msgError);
    }
    return correct;
}

int CPfPhaseTypesDAOSQLiteEntity::callbackRegister(void *object, int nColumns, char **vColumn, char **sColumn)
{
    if( object!=NULL ){
        CPfPhaseTypes *destiny = (CPfPhaseTypes*)object;
        for( int i=0; i<nColumns; i++ ){
            if( strcmp(sColumn[i], "S_PHASE_TYPE")==0 ){
                destiny->setSPhaseType_str((vColumn[i]==NULL)?"":vColumn[i]);
            }else if( strcmp(sColumn[i], "X_PHASE_TYPE")==0 ){
                destiny->setXPhaseType_str((vColumn[i]==NULL)?"":vColumn[i]);
            }
        }
    }
    return -1; // Abort, don't load more rows
}

int CPfPhaseTypesDAOSQLiteEntity::callbackVector(void *object, int nColumns, char **vColumn, char **sColumn)
{
    if( object!=NULL ){
        std::vector<CPfPhaseTypes*> *container = (std::vector<CPfPhaseTypes*> *)object;
        CPfPhaseTypes *destiny = new CPfPhaseTypes();
        for( int i=0; i<nColumns; i++ ){
            if( strcmp(sColumn[i], "S_PHASE_TYPE")==0 ){
                destiny->setSPhaseType_str((vColumn[i]==NULL)?"":vColumn[i]);
            }else if( strcmp(sColumn[i], "X_PHASE_TYPE")==0 ){
                destiny->setXPhaseType_str((vColumn[i]==NULL)?"":vColumn[i]);
            }
        }
        container->push_back(destiny);
    }
    return 0; // All OK
}

