/******************************************************************************
* Copyright (C) 2010 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.23                                                         *
******************************************************************************/

#include <stdlib.h>
#include <string.h>

#include "CPfPhaseRoundsDAOSQLiteEntity.h"
#include "../../../../../exceptions/PFException.h"
#include "../../../../../utils/CLog.h"

CPfPhaseRoundsDAOSQLiteEntity::CPfPhaseRoundsDAOSQLiteEntity(sqlite3 *database)
{
    m_database = database;
}

CPfPhaseRoundsDAOSQLiteEntity::~CPfPhaseRoundsDAOSQLiteEntity()
{
}

void CPfPhaseRoundsDAOSQLiteEntity::setSQLite(sqlite3 *database)
{
    m_database = database;
}

bool CPfPhaseRoundsDAOSQLiteEntity::deleteReg(CPfPhaseRounds *reg)
{
    std::string sql("DELETE FROM PF_PHASE_ROUNDS WHERE X_PHASE_ROUND=");
    sql += "'"+reg->getXPhaseRound_str()+"'";
    return exec(sql);
}

bool CPfPhaseRoundsDAOSQLiteEntity::insertReg(CPfPhaseRounds *reg)
{
    std::string sql("INSERT INTO PF_PHASE_ROUNDS (X_FK_COMPETITION_PHASE,N_ORDER,S_PHASE_ROUND) VALUES (");
    sql += (reg->getXFkCompetitionPhase_str()=="")?"NULL":"'"+reg->getXFkCompetitionPhase_str()+"'";
    sql += (reg->getNOrder_str()=="")?",NULL":",'"+reg->getNOrder_str()+"'";
    sql += (reg->getSPhaseRound_str()=="")?",NULL":",'"+reg->getSPhaseRound_str()+"'";
    sql += ")";
    if( exec(sql) ){
        reg->setXPhaseRound(sqlite3_last_insert_rowid(m_database));
        return true;
    }else{
        return false;
    }
}

bool CPfPhaseRoundsDAOSQLiteEntity::updateReg(CPfPhaseRounds *reg)
{
    std::string sql("UPDATE PF_PHASE_ROUNDS SET ");
    sql += (reg->getXFkCompetitionPhase_str()=="")?" X_FK_COMPETITION_PHASE=NULL":" X_FK_COMPETITION_PHASE='"+reg->getXFkCompetitionPhase_str()+"'";
    sql += (reg->getNOrder_str()=="")?",N_ORDER=NULL":",N_ORDER='"+reg->getNOrder_str()+"'";
    sql += (reg->getSPhaseRound_str()=="")?",S_PHASE_ROUND=NULL":",S_PHASE_ROUND='"+reg->getSPhaseRound_str()+"'";
    sql += (reg->getXPhaseRound_str()=="")?",X_PHASE_ROUND=NULL":",X_PHASE_ROUND='"+reg->getXPhaseRound_str()+"'";
    sql += " WHERE X_PHASE_ROUND='"+reg->getXPhaseRound_str()+"'";
    return exec(sql);
}

void CPfPhaseRoundsDAOSQLiteEntity::freeVector(std::vector<CPfPhaseRounds*>* vector )
{
    std::vector<CPfPhaseRounds*>::iterator it;
    for( it=vector->begin(); it!=vector->end(); it++ ){
        delete (*it);
        (*it) = NULL;
    }
    delete vector;
}

CPfPhaseRounds* CPfPhaseRoundsDAOSQLiteEntity::loadRegister(const std::string &sql)
{
    if( m_database==NULL ){
        throw PFEXCEPTION("No database connection.");
    }

    char *msgError = NULL;
    CPfPhaseRounds *destiny = new CPfPhaseRounds();
    int result = sqlite3_exec(m_database, sql.c_str(), callbackRegister, destiny, &msgError);
    if( result!=SQLITE_OK && result!=SQLITE_ABORT ){
        LOG_ERROR("Error in SQL: \"%s\" --> \"%s\"", sql.c_str(), msgError);
    }
    if( msgError!=NULL ){ 
        sqlite3_free(msgError);
    }
    return destiny;
}

std::vector<CPfPhaseRounds*> * CPfPhaseRoundsDAOSQLiteEntity::loadVector(const std::string &sql)
{
    if( m_database==NULL ){
        throw PFEXCEPTION("No database connection.");
    }

    char *msgError = NULL;
    std::vector<CPfPhaseRounds*> *container = new std::vector<CPfPhaseRounds*>;
    int result = sqlite3_exec(m_database, sql.c_str(), callbackVector, container, &msgError);
    if( result!=SQLITE_OK ){
        LOG_ERROR("Error in SQL: \"%s\" --> \"%s\"", sql.c_str(), msgError);
    }
    if( msgError!=NULL ){ 
        sqlite3_free(msgError);
    }
    return container;
}

bool CPfPhaseRoundsDAOSQLiteEntity::exec(const std::string &sql)
{
    if( m_database==NULL ){
        throw PFEXCEPTION("No database connection.");
    }

    char *msgError = NULL;
    bool correct = true;
    int result = sqlite3_exec(m_database, sql.c_str(), NULL, NULL, &msgError);
    if( result!=SQLITE_OK ){
        LOG_ERROR("Error in SQL: \"%s\" --> \"%s\"", sql.c_str(), msgError);
        correct = false;
    }
    if( msgError!=NULL ){ 
        sqlite3_free(msgError);
    }
    return correct;
}

int CPfPhaseRoundsDAOSQLiteEntity::callbackRegister(void *object, int nColumns, char **vColumn, char **sColumn)
{
    if( object!=NULL ){
        CPfPhaseRounds *destiny = (CPfPhaseRounds*)object;
        for( int i=0; i<nColumns; i++ ){
            if( strcmp(sColumn[i], "X_FK_COMPETITION_PHASE")==0 ){
                destiny->setXFkCompetitionPhase_str((vColumn[i]==NULL)?"":vColumn[i]);
            }else if( strcmp(sColumn[i], "N_ORDER")==0 ){
                destiny->setNOrder_str((vColumn[i]==NULL)?"":vColumn[i]);
            }else if( strcmp(sColumn[i], "S_PHASE_ROUND")==0 ){
                destiny->setSPhaseRound_str((vColumn[i]==NULL)?"":vColumn[i]);
            }else if( strcmp(sColumn[i], "X_PHASE_ROUND")==0 ){
                destiny->setXPhaseRound_str((vColumn[i]==NULL)?"":vColumn[i]);
            }
        }
    }
    return -1; // Abort, don't load more rows
}

int CPfPhaseRoundsDAOSQLiteEntity::callbackVector(void *object, int nColumns, char **vColumn, char **sColumn)
{
    if( object!=NULL ){
        std::vector<CPfPhaseRounds*> *container = (std::vector<CPfPhaseRounds*> *)object;
        CPfPhaseRounds *destiny = new CPfPhaseRounds();
        for( int i=0; i<nColumns; i++ ){
            if( strcmp(sColumn[i], "X_FK_COMPETITION_PHASE")==0 ){
                destiny->setXFkCompetitionPhase_str((vColumn[i]==NULL)?"":vColumn[i]);
            }else if( strcmp(sColumn[i], "N_ORDER")==0 ){
                destiny->setNOrder_str((vColumn[i]==NULL)?"":vColumn[i]);
            }else if( strcmp(sColumn[i], "S_PHASE_ROUND")==0 ){
                destiny->setSPhaseRound_str((vColumn[i]==NULL)?"":vColumn[i]);
            }else if( strcmp(sColumn[i], "X_PHASE_ROUND")==0 ){
                destiny->setXPhaseRound_str((vColumn[i]==NULL)?"":vColumn[i]);
            }
        }
        container->push_back(destiny);
    }
    return 0; // All OK
}

