/******************************************************************************
* Copyright (C) 2010 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.23                                                         *
******************************************************************************/

#include <stdlib.h>
#include <string.h>

#include "CPfTeamsByCompetitionPhaseDAOSQLiteEntity.h"
#include "../../../../../exceptions/PFException.h"
#include "../../../../../utils/CLog.h"

CPfTeamsByCompetitionPhaseDAOSQLiteEntity::CPfTeamsByCompetitionPhaseDAOSQLiteEntity(sqlite3 *database)
{
    m_database = database;
}

CPfTeamsByCompetitionPhaseDAOSQLiteEntity::~CPfTeamsByCompetitionPhaseDAOSQLiteEntity()
{
}

void CPfTeamsByCompetitionPhaseDAOSQLiteEntity::setSQLite(sqlite3 *database)
{
    m_database = database;
}

bool CPfTeamsByCompetitionPhaseDAOSQLiteEntity::deleteReg(CPfTeamsByCompetitionPhase *reg)
{
    std::string sql("DELETE FROM PF_TEAMS_BY_COMPETITION_PHASE WHERE X_TEAM_BY_COMPETITION_PHASE=");
    sql += "'"+reg->getXTeamByCompetitionPhase_str()+"'";
    return exec(sql);
}

bool CPfTeamsByCompetitionPhaseDAOSQLiteEntity::insertReg(CPfTeamsByCompetitionPhase *reg)
{
    std::string sql("INSERT INTO PF_TEAMS_BY_COMPETITION_PHASE (X_FK_COMPETITION_PHASE_BY_SEASON,X_FK_TEAM) VALUES (");
    sql += (reg->getXFkCompetitionPhaseBySeason_str()=="")?"NULL":"'"+reg->getXFkCompetitionPhaseBySeason_str()+"'";
    sql += (reg->getXFkTeam_str()=="")?",NULL":",'"+reg->getXFkTeam_str()+"'";
    sql += ")";
    if( exec(sql) ){
        reg->setXTeamByCompetitionPhase(sqlite3_last_insert_rowid(m_database));
        return true;
    }else{
        return false;
    }
}

bool CPfTeamsByCompetitionPhaseDAOSQLiteEntity::updateReg(CPfTeamsByCompetitionPhase *reg)
{
    std::string sql("UPDATE PF_TEAMS_BY_COMPETITION_PHASE SET ");
    sql += (reg->getXTeamByCompetitionPhase_str()=="")?" X_TEAM_BY_COMPETITION_PHASE=NULL":" X_TEAM_BY_COMPETITION_PHASE='"+reg->getXTeamByCompetitionPhase_str()+"'";
    sql += (reg->getXFkCompetitionPhaseBySeason_str()=="")?",X_FK_COMPETITION_PHASE_BY_SEASON=NULL":",X_FK_COMPETITION_PHASE_BY_SEASON='"+reg->getXFkCompetitionPhaseBySeason_str()+"'";
    sql += (reg->getXFkTeam_str()=="")?",X_FK_TEAM=NULL":",X_FK_TEAM='"+reg->getXFkTeam_str()+"'";
    sql += " WHERE X_TEAM_BY_COMPETITION_PHASE='"+reg->getXTeamByCompetitionPhase_str()+"'";
    return exec(sql);
}

void CPfTeamsByCompetitionPhaseDAOSQLiteEntity::freeVector(std::vector<CPfTeamsByCompetitionPhase*>* vector )
{
    std::vector<CPfTeamsByCompetitionPhase*>::iterator it;
    for( it=vector->begin(); it!=vector->end(); it++ ){
        delete (*it);
        (*it) = NULL;
    }
    delete vector;
}

CPfTeamsByCompetitionPhase* CPfTeamsByCompetitionPhaseDAOSQLiteEntity::loadRegister(const std::string &sql)
{
    if( m_database==NULL ){
        throw PFEXCEPTION("No database connection.");
    }

    char *msgError = NULL;
    CPfTeamsByCompetitionPhase *destiny = new CPfTeamsByCompetitionPhase();
    int result = sqlite3_exec(m_database, sql.c_str(), callbackRegister, destiny, &msgError);
    if( result!=SQLITE_OK && result!=SQLITE_ABORT ){
        LOG_ERROR("Error in SQL: \"%s\" --> \"%s\"", sql.c_str(), msgError);
    }
    if( msgError!=NULL ){ 
        sqlite3_free(msgError);
    }
    return destiny;
}

std::vector<CPfTeamsByCompetitionPhase*> * CPfTeamsByCompetitionPhaseDAOSQLiteEntity::loadVector(const std::string &sql)
{
    if( m_database==NULL ){
        throw PFEXCEPTION("No database connection.");
    }

    char *msgError = NULL;
    std::vector<CPfTeamsByCompetitionPhase*> *container = new std::vector<CPfTeamsByCompetitionPhase*>;
    int result = sqlite3_exec(m_database, sql.c_str(), callbackVector, container, &msgError);
    if( result!=SQLITE_OK ){
        LOG_ERROR("Error in SQL: \"%s\" --> \"%s\"", sql.c_str(), msgError);
    }
    if( msgError!=NULL ){ 
        sqlite3_free(msgError);
    }
    return container;
}

bool CPfTeamsByCompetitionPhaseDAOSQLiteEntity::exec(const std::string &sql)
{
    if( m_database==NULL ){
        throw PFEXCEPTION("No database connection.");
    }

    char *msgError = NULL;
    bool correct = true;
    int result = sqlite3_exec(m_database, sql.c_str(), NULL, NULL, &msgError);
    if( result!=SQLITE_OK ){
        LOG_ERROR("Error in SQL: \"%s\" --> \"%s\"", sql.c_str(), msgError);
        correct = false;
    }
    if( msgError!=NULL ){ 
        sqlite3_free(msgError);
    }
    return correct;
}

int CPfTeamsByCompetitionPhaseDAOSQLiteEntity::callbackRegister(void *object, int nColumns, char **vColumn, char **sColumn)
{
    if( object!=NULL ){
        CPfTeamsByCompetitionPhase *destiny = (CPfTeamsByCompetitionPhase*)object;
        for( int i=0; i<nColumns; i++ ){
            if( strcmp(sColumn[i], "X_TEAM_BY_COMPETITION_PHASE")==0 ){
                destiny->setXTeamByCompetitionPhase_str((vColumn[i]==NULL)?"":vColumn[i]);
            }else if( strcmp(sColumn[i], "X_FK_COMPETITION_PHASE_BY_SEASON")==0 ){
                destiny->setXFkCompetitionPhaseBySeason_str((vColumn[i]==NULL)?"":vColumn[i]);
            }else if( strcmp(sColumn[i], "X_FK_TEAM")==0 ){
                destiny->setXFkTeam_str((vColumn[i]==NULL)?"":vColumn[i]);
            }
        }
    }
    return -1; // Abort, don't load more rows
}

int CPfTeamsByCompetitionPhaseDAOSQLiteEntity::callbackVector(void *object, int nColumns, char **vColumn, char **sColumn)
{
    if( object!=NULL ){
        std::vector<CPfTeamsByCompetitionPhase*> *container = (std::vector<CPfTeamsByCompetitionPhase*> *)object;
        CPfTeamsByCompetitionPhase *destiny = new CPfTeamsByCompetitionPhase();
        for( int i=0; i<nColumns; i++ ){
            if( strcmp(sColumn[i], "X_TEAM_BY_COMPETITION_PHASE")==0 ){
                destiny->setXTeamByCompetitionPhase_str((vColumn[i]==NULL)?"":vColumn[i]);
            }else if( strcmp(sColumn[i], "X_FK_COMPETITION_PHASE_BY_SEASON")==0 ){
                destiny->setXFkCompetitionPhaseBySeason_str((vColumn[i]==NULL)?"":vColumn[i]);
            }else if( strcmp(sColumn[i], "X_FK_TEAM")==0 ){
                destiny->setXFkTeam_str((vColumn[i]==NULL)?"":vColumn[i]);
            }
        }
        container->push_back(destiny);
    }
    return 0; // All OK
}

