/******************************************************************************
* Copyright (C) 2010 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.23                                                         *
******************************************************************************/

#ifndef CPFPHASEROUNDSDAOSQLITE_H_
#define CPFPHASEROUNDSDAOSQLITE_H_

#include <string>
#include <sqlite3.h>

#include "entity/CPfPhaseRoundsDAOSQLiteEntity.h"
#include "../../bean/CPfPhaseRounds.h"

class CPfPhaseRoundsDAOSQLite : public CPfPhaseRoundsDAOSQLiteEntity
{
public:
    CPfPhaseRoundsDAOSQLite(sqlite3 *database);
    virtual ~CPfPhaseRoundsDAOSQLite();

    virtual std::vector<CPfPhaseRounds*>* findByXFkCompetitionPhase(int XFkCompetitionPhase);
    virtual std::vector<CPfPhaseRounds*>* findByXFkCompetitionPhase(const std::string &XFkCompetitionPhase);
    virtual CPfPhaseRounds* findByXPhaseRound(int XPhaseRound);
    virtual CPfPhaseRounds* findByXPhaseRound(const std::string &XPhaseRound);
    virtual std::vector<CPfPhaseRounds*>* findByXFkCompetition(int XFkCompetition);
    virtual std::vector<CPfPhaseRounds*>* findByXFkCompetition(const std::string &XFkCompetition);
    virtual CPfPhaseRounds* findLastPhaseRound(int XFkCompetition, int XSeason);
    virtual CPfPhaseRounds* findLastPhaseRound(const std::string &XFkCompetition, const std::string &XSeason);

};
#endif /*CPFPHASEROUNDSDAOSQLITE_H_*/
