/******************************************************************************
* Copyright (C) 2008 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.20                                                         *
******************************************************************************/

#include <iostream>
#include <sstream>

#include "CPfRegisteredTeamsDAOSQLite.h"

CPfRegisteredTeamsDAOSQLite::CPfRegisteredTeamsDAOSQLite(sqlite3 *database)
  : CPfRegisteredTeamsDAOSQLiteEntity(database)
{
}

CPfRegisteredTeamsDAOSQLite::~CPfRegisteredTeamsDAOSQLite()
{
}

CPfRegisteredTeams* CPfRegisteredTeamsDAOSQLite::findByXRegisteredTeam(int XRegisteredTeam)
{
    std::ostringstream stream;
    stream << XRegisteredTeam;
    return findByXRegisteredTeam(stream.str());
}

CPfRegisteredTeams* CPfRegisteredTeamsDAOSQLite::findByXRegisteredTeam(const std::string &XRegisteredTeam)
{
    std::string sql("SELECT * FROM PF_REGISTERED_TEAMS WHERE ");
    sql = sql+"X_REGISTERED_TEAM='"+XRegisteredTeam+"'";
    return loadRegister(sql);
}

CPfRegisteredTeams* CPfRegisteredTeamsDAOSQLite::findByXFkCompetition(int XFkCompetition)
{
    std::ostringstream stream;
    stream << XFkCompetition;
    return findByXFkCompetition(stream.str());
}

CPfRegisteredTeams* CPfRegisteredTeamsDAOSQLite::findByXFkCompetition(const std::string &XFkCompetition)
{
    std::string sql("SELECT * FROM PF_REGISTERED_TEAMS WHERE ");
    sql = sql+"X_FK_COMPETITION='"+XFkCompetition+"'";
    return loadRegister(sql);
}

CPfRegisteredTeams* CPfRegisteredTeamsDAOSQLite::findByXFkTeam(int XFkTeam)
{
    std::ostringstream stream;
    stream << XFkTeam;
    return findByXFkTeam(stream.str());
}

CPfRegisteredTeams* CPfRegisteredTeamsDAOSQLite::findByXFkTeam(const std::string &XFkTeam)
{
    std::string sql("SELECT * FROM PF_REGISTERED_TEAMS WHERE ");
    sql = sql+"X_FK_TEAM='"+XFkTeam+"'";
    return loadRegister(sql);
}

