/******************************************************************************
* Copyright (C) 2009 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.23                                                         *
******************************************************************************/

#include <iostream>
#include <sstream>

#include "CPfStrategicPositionDAOSQLite.h"

CPfStrategicPositionDAOSQLite::CPfStrategicPositionDAOSQLite(sqlite3 *database)
  : CPfStrategicPositionDAOSQLiteEntity(database)
{
}

CPfStrategicPositionDAOSQLite::~CPfStrategicPositionDAOSQLite()
{
}

CPfStrategicPosition* CPfStrategicPositionDAOSQLite::findByXFkFormation(int XFkFormation)
{
    std::ostringstream stream;
    stream << XFkFormation;
    return findByXFkFormation(stream.str());
}

CPfStrategicPosition* CPfStrategicPositionDAOSQLite::findByXFkFormation(const std::string &XFkFormation)
{
    std::string sql("SELECT * FROM PF_STRATEGIC_POSITION WHERE ");
    sql = sql+"X_FK_FORMATION='"+XFkFormation+"'";
    return loadRegister(sql);
}

CPfStrategicPosition* CPfStrategicPositionDAOSQLite::findByXFkRole(int XFkRole)
{
    std::ostringstream stream;
    stream << XFkRole;
    return findByXFkRole(stream.str());
}

CPfStrategicPosition* CPfStrategicPositionDAOSQLite::findByXFkRole(const std::string &XFkRole)
{
    std::string sql("SELECT * FROM PF_STRATEGIC_POSITION WHERE ");
    sql = sql+"X_FK_ROLE='"+XFkRole+"'";
    return loadRegister(sql);
}

CPfStrategicPosition* CPfStrategicPositionDAOSQLite::findByXStrategicPosition(int XStrategicPosition)
{
    std::ostringstream stream;
    stream << XStrategicPosition;
    return findByXStrategicPosition(stream.str());
}

CPfStrategicPosition* CPfStrategicPositionDAOSQLite::findByXStrategicPosition(const std::string &XStrategicPosition)
{
    std::string sql("SELECT * FROM PF_STRATEGIC_POSITION WHERE ");
    sql = sql+"X_STRATEGIC_POSITION='"+XStrategicPosition+"'";
    return loadRegister(sql);
}

