/******************************************************************************
* Copyright (C) 2010 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.23                                                         *
******************************************************************************/

#ifndef CPFTEAMSBYCOMPETITIONPHASEDAOSQLITE_H_
#define CPFTEAMSBYCOMPETITIONPHASEDAOSQLITE_H_

#include <string>
#include <sqlite3.h>

#include "entity/CPfTeamsByCompetitionPhaseDAOSQLiteEntity.h"
#include "../../bean/CPfTeamsByCompetitionPhase.h"

class CPfTeamsByCompetitionPhaseDAOSQLite : public CPfTeamsByCompetitionPhaseDAOSQLiteEntity
{
public:
    CPfTeamsByCompetitionPhaseDAOSQLite(sqlite3 *database);
    virtual ~CPfTeamsByCompetitionPhaseDAOSQLite();

    virtual CPfTeamsByCompetitionPhase* findByXTeamByCompetitionPhase(int XTeamByCompetitionPhase);
    virtual CPfTeamsByCompetitionPhase* findByXTeamByCompetitionPhase(const std::string &XTeamByCompetitionPhase);
    virtual CPfTeamsByCompetitionPhase* findByXFkCompetitionPhaseBySeason(int XFkCompetitionPhaseBySeason);
    virtual CPfTeamsByCompetitionPhase* findByXFkCompetitionPhaseBySeason(const std::string &XFkCompetitionPhaseBySeason);
    virtual CPfTeamsByCompetitionPhase* findByXFkTeam(int XFkTeam);
    virtual CPfTeamsByCompetitionPhase* findByXFkTeam(const std::string &XFkTeam);

};
#endif /*CPFTEAMSBYCOMPETITIONPHASEDAOSQLITE_H_*/
