/******************************************************************************
* Copyright (C) 2010 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.23                                                         *
******************************************************************************/

#include <iostream>
#include <sstream>

#include "CPfTeamsByCompetitionPhaseDAOSQLite.h"

CPfTeamsByCompetitionPhaseDAOSQLite::CPfTeamsByCompetitionPhaseDAOSQLite(sqlite3 *database)
  : CPfTeamsByCompetitionPhaseDAOSQLiteEntity(database)
{
}

CPfTeamsByCompetitionPhaseDAOSQLite::~CPfTeamsByCompetitionPhaseDAOSQLite()
{
}

CPfTeamsByCompetitionPhase* CPfTeamsByCompetitionPhaseDAOSQLite::findByXTeamByCompetitionPhase(int XTeamByCompetitionPhase)
{
    std::ostringstream stream;
    stream << XTeamByCompetitionPhase;
    return findByXTeamByCompetitionPhase(stream.str());
}

CPfTeamsByCompetitionPhase* CPfTeamsByCompetitionPhaseDAOSQLite::findByXTeamByCompetitionPhase(const std::string &XTeamByCompetitionPhase)
{
    std::string sql("SELECT * FROM PF_TEAMS_BY_COMPETITION_PHASE WHERE ");
    sql = sql+"X_TEAM_BY_COMPETITION_PHASE='"+XTeamByCompetitionPhase+"'";
    return loadRegister(sql);
}

CPfTeamsByCompetitionPhase* CPfTeamsByCompetitionPhaseDAOSQLite::findByXFkCompetitionPhaseBySeason(int XFkCompetitionPhaseBySeason)
{
    std::ostringstream stream;
    stream << XFkCompetitionPhaseBySeason;
    return findByXFkCompetitionPhaseBySeason(stream.str());
}

CPfTeamsByCompetitionPhase* CPfTeamsByCompetitionPhaseDAOSQLite::findByXFkCompetitionPhaseBySeason(const std::string &XFkCompetitionPhaseBySeason)
{
    std::string sql("SELECT * FROM PF_TEAMS_BY_COMPETITION_PHASE WHERE ");
    sql = sql+"X_FK_COMPETITION_PHASE_BY_SEASON='"+XFkCompetitionPhaseBySeason+"'";
    return loadRegister(sql);
}

CPfTeamsByCompetitionPhase* CPfTeamsByCompetitionPhaseDAOSQLite::findByXFkTeam(int XFkTeam)
{
    std::ostringstream stream;
    stream << XFkTeam;
    return findByXFkTeam(stream.str());
}

CPfTeamsByCompetitionPhase* CPfTeamsByCompetitionPhaseDAOSQLite::findByXFkTeam(const std::string &XFkTeam)
{
    std::string sql("SELECT * FROM PF_TEAMS_BY_COMPETITION_PHASE WHERE ");
    sql = sql+"X_FK_TEAM='"+XFkTeam+"'";
    return loadRegister(sql);
}

