/******************************************************************************
* Copyright (C) 2008 - Ikaro Games   www.ikarogames.com                       *
*                                                                             *
* This program is free software; you can redistribute it and/or               *
* modify it under the terms of the GNU General Public License                 *
* as published by the Free Software Foundation; either version 2              *
* of the License, or (at your option) any later version.                      *
*                                                                             *
* This program is distributed in the hope that it will be useful,             *
* but WITHOUT ANY WARRANTY; without even the implied warranty of              *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
* GNU General Public License for more details.                                *
*                                                                             *
* You should have received a copy of the GNU General Public License           *
* along with this program; if not, write to the Free Software                 *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA. *
*                                                                             *
*                                                                             *
*       generated by dia/DAOcodegen.py                                        *
*       Version: 1.3                                                          *
******************************************************************************/

#ifndef IPFEQUIPOSDAO_H_
#define IPFEQUIPOSDAO_H_

#include <string>

#include "../bean/CPfEquipos.h"

class IPfEquiposDAO
{
public:
    IPfEquiposDAO(){}
    virtual ~IPfEquiposDAO(){}

    virtual bool deleteReg(CPfEquipos *reg) =0;
    virtual bool insertReg(CPfEquipos *reg) =0;
    virtual bool updateReg(CPfEquipos *reg) =0;

    virtual CPfEquipos* findByXFkPais(int XFkPais) =0;
    virtual CPfEquipos* findByXFkPais(const std::string XFkPais) =0;
    virtual CPfEquipos* findByXEquipo(int XEquipo) =0;
    virtual CPfEquipos* findByXEquipo(const std::string XEquipo) =0;

};
#endif /*IPFEQUIPOSDAO_H_*/
